baseURL: https://semjonov.de/
title: semjonov.de blog

params:
  author: Anton Semjonov
  license: licensed under [Creative Commons BY-SA 4.0](/license.html)
  repository: https://github.com/ansemjo/hugo-semjonov.de

theme: plain
paginate: 5

enableGitInfo: no
disableHugoGeneratorInject: yes

disableKinds:
  - sitemap
taxonomies:
  tags: tags
permalinks:
  post: /:section/:year-:month/:slug

menu:
  main:

    - name: Home
      weight: 1
      url: /

    - name: Tags
      weight: 2
      url: /tags/

blackfriday:
  noreferrerLinks:  yes
