title = "semjonov.de"
theme = "book"
baseUrl = "https://semjonov.de/"

paginate = 8
enableGitInfo = true
rssLimit = 20

pygmentsUseClasses = true
pygmentsCodefences = true
pygmentsCodefencesGuessSyntax = true

[params]
  author = "Anton Semjonov"
  license = "licensed under [Creative Commons BY-SA 4.0](/license)"

  BookTheme = "auto"
  BookToC = true
  BookRepo = "https://github.com/ansemjo/blog"
  BookEditPath = "edit/master/content"
  BookDateFormat = "January 2, 2006"
  BookSearch = true
  BookComments = false
  BookPortableLinks = true

[taxonomies]
  tag = "tags"

[permalinks]
  posts = "/:section/:year-:month/:slug"

[blackfriday]
  fractions = false
  noreferrerLinks = true

[markup.tableOfContents]
  startLevel = 2

[markup.goldmark.renderer]
  unsafe = true
