---
# general settings
baseURL: https://semjonov.de/
title: semjonov.de
LanguageCode: en
theme: hackcss
Paginate: 5
enableGitInfo: true
disableKinds:
  - RSS


# building directories
contentDir: content
publishDir: public


# url structure
uglyURLs: true
permalinks:
  #post: /:section/:slug


# permanent menu links
# others can be added in post frontmatter
menu:
  main:

    - name: Home
      weight: 1
      url: /

    - name: Tags
      weight: 2
      url: /tags.html

    - name: Categories
      weight: 3
      url: /categories.html



# miscellaneous site settings
params:
  title: 'semjonov.de'
  author: Anton Semjonov
  license: "Licensed under [Creative Commons BY-SA 4.0](/license.html)"
  repository: https://github.com/ansemjo/hugo-website


# markdown parser
blackfriday:
  smarypants:     true
  angledQuotes:   true
  fractions:      true

...
