title = "semjonov.de blog"
theme = "plain"
baseUrl = "https://semjonov.de/"

paginate = 5
enableGitInfo = true
rssLimit = 20

pygmentsUseClasses = true
pygmentsCodefences = true
pygmentsCodefencesGuessSyntax = true

[params]
  author = "Anton Semjonov"
  license = "licensed under [Creative Commons BY-SA 4.0](/license)"
  repository = "https://github.com/ansemjo/blog"

[taxonomies]
  tag = "tags"

[permalinks]
  post = "/:section/:year-:month/:slug"

[blackfriday]
  fractions = false
  noreferrerLinks = true

[markup.goldmark.renderer]
  unsafe = true

[menu]

  [[menu.main]]
    name = "Home"
    weight = 1
    url = "/"

  [[menu.main]]
    name = "Tags"
    weight = 2
    url = "/tags/"
