#!/usr/bin/env ansible-playbook
---

- hosts: all
  gather_facts: no
  become: yes
  vars:
    webroot: /srv/www/semjonov.de

  handlers:

    - name: restorecon
      shell: 'restorecon -R -v "{{ webroot }}"'

  tasks:

    - name: packages are installed
      tags: [ install ]
      yum:
        name: [ nginx, rsync ]
        state: present

    - name: selinux file context definition present
      tags: [ install ]
      sefcontext:
        target: "{{ webroot }}(/.*)?"
        setype: httpd_sys_content_t
        state: present

    - name: webroot directory created
      tags: [ install ]
      file:
        path: "{{ webroot }}"
        state: directory
        owner: root
        group: root
        mode: 0755
      notify: restorecon

    - name: built static files are synchronized
      tags: [ install, deploy ]
      synchronize:
        src: public/
        dest: "{{ webroot }}"
        owner: no
        group: no
      notify: restorecon

